### ISSUE TITLE
Failed to load a language-lsl2 package grammar

### ISSUE THREAD

**Issue by X00LA** [Jomik/atom-language-lsl2#1]
[Enter steps to reproduce:]

1. Installed linter-sls2 and autoinstalled the dependencies.
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: WORKSTATION
**Thrown From**: [language-lsl2](https://github.com/jomik/atom-language-lsl2) package 0.0.1

### Stack Trace

Failed to load a language-lsl2 package grammar

```
At %1 ist keine zulässige Win32-Anwendung.
\\?\C:\Users\Markus\.atom\packages\language-lsl2\node_modules\tree-sitter-lsl2\build\Release\tree_sitter_lsl2_binding.node in C:\Users\Markus\.atom\packages\language-lsl2\grammars\lsl2.json

Error: %1 ist keine zulässige Win32-Anwendung.
\\?\C:\Users\USER\.atom\packages\language-lsl2\node_modules\tree-sitter-lsl2\build\Release\tree_sitter_lsl2_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/language-lsl2/node_modules/tree-sitter-lsl2/index.js:2:20)
    at /packages/language-lsl2/node_modules/tree-sitter-lsl2/index.js:7:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:1:623185)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:2955849)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:357769)
    at l.readFile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:357610)
    at u (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:576950)
    at ~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:578203
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
  at /packages/language-lsl2/grammars/lsl2.json:1:1
```

### Commands

```
  4x -5:10.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-glsl 0.2.3 
language-glsl 2.0.4 
language-lsl2 0.0.1 
linter 2.2.0 
linter-lsl2 0.0.2 
```

**Comment by stevencoulter** [comment]
Same issue on OSX.  I built the tree sitter (https://github.com/Jomik/tree-sitter-lsl2) with npm and copied it over to ~/.atom/packages/language-lsl2/node_modules/tree-sitter-lsl2.  This corrected the issue for me.

**Comment by furroy** [comment]
help. i am also stuck on this issue.  i tried to download and build tree-sitter-lsl2 but nothing seems to happen when i do npm build on it.

**Comment by Jomik** [comment]
Hmm, I do recall having an issue myself as well. Sadly I switched away from Atom again :/

**Comment by furroy** [comment]
i got a little father trying to build it. but looks like i need to install python???

C:\Users\furroy\OneDrive\Documents\tree-sitter-lsl2\node_modules\tree-sitter-cli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\furroy\OneDrive\Documents\tree-sitter-lsl2\node_modules\tree-sitter-cli
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-cli@0.13.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter-cli@0.13.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\furroy\AppData\Roaming\npm-cache\_logs\2019-03-01T13_40_16_927Z-debug.log

**Comment by zylipan** [comment]
<img width="460" alt="Screen Shot 2020-05-04 at 7 35 20 AM" src="https://user-images.githubusercontent.com/63137818/80977641-ddfd3500-8dd9-11ea-8b65-4424c14d3118.png">

Please help to solve the problems.

**Comment by IASheer** [comment]
[Enter steps to reproduce:]
**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [language-lsl2](https://github.com/jomik/atom-language-lsl2) package 0.0.1


### Stack Trace

Failed to load a language-lsl2 package grammar

```
At \\?\C:\Users\ivans\.atom\packages\language-lsl2\node_modules\tree-sitter-lsl2\build\Release\tree_sitter_lsl2_binding.node is not a valid Win32 application.
\\?\C:\Users\ivans\.atom\packages\language-lsl2\node_modules\tree-sitter-lsl2\build\Release\tree_sitter_lsl2_binding.node in C:\Users\ivans\.atom\packages\language-lsl2\grammars\lsl2.json

Error: \\?\C:\Users\ivans\.atom\packages\language-lsl2\node_modules\tree-sitter-lsl2\build\Release\tree_sitter_lsl2_binding.node is not a valid Win32 application.
\\?\C:\Users\ivans\.atom\packages\language-lsl2\node_modules\tree-sitter-lsl2\build\Release\tree_sitter_lsl2_binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/language-lsl2/node_modules/tree-sitter-lsl2/index.js:2:20)
    at /packages/language-lsl2/node_modules/tree-sitter-lsl2/index.js:7:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3209684)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:360193)
    at l.readFile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:360034)
    at u (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:580702)
    at ~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:581955
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
  at /packages/language-lsl2/grammars/lsl2.json:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.18 
busy-signal 2.0.1 
intentions 1.1.5 
language-lsl 2.2.0 
language-lsl2 0.0.1 
linter 2.3.1 
linter-lsl2 0.0.2 
linter-ui-default 1.8.1 
```
